### ISSUE TITLE
A code quesition

### ISSUE THREAD

**Issue by iomeone** [Musicoll/Kiwi#155]
https://github.com/Musicoll/Kiwi/blob/8f1ef8d8780b44a8a065f66832585941c7bc238f/Client/Source/KiwiApp_Network/KiwiApp_Api.cpp#L713

the code  `user.m_api_version = Api::getJsonValue<int>(j, "__v");`
the m_api_version is private, how can you access an private variable?

**Comment by eliottparis** [comment]
@iomeone The `from_json` function is declared as a friend [here](https://github.com/Musicoll/Kiwi/blob/8f1ef8d8780b44a8a065f66832585941c7bc238f/Client/Source/KiwiApp_Network/KiwiApp_Api.h#L283).

**Comment by iomeone** [comment]
Ok, now I know! thank you ~
